@echo off
echo Starting Job Portal Application...

echo Starting Backend Server on port 5000...
start cmd /k "cd backend && python app.py"

echo Waiting for backend to initialize...
timeout /t 5

echo Starting Frontend Server...
start cmd /k "cd frontend && npm start"

echo Both servers are starting. Please wait...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000